### ISSUE TITLE
Add domain request

### ISSUE THREAD

**Issue by willnorris** [remy/unrot.link#5]
Super cool idea, Remy!  I'd love to use it on https://willnorris.com/.  I'll likely proxy it through my own reverse proxy so that client requests go through my own domain and I don't have to adjust CSP headers (similar to what I do for [webmentions](https://github.com/willnorris/willnorris.com/blob/main/etc/Caddyfile#L136-L146) and [csp reports](https://github.com/willnorris/willnorris.com/blob/main/etc/Caddyfile#L159-L169)).  I'm not sure if that will impact how you do the allow listing?  Thanks!

**Comment by remy** [comment]
That's going live now. I've no idea how a proxy will work - though the service does rely on the referral header to check access (the source code is linked throughout the interactive demo page). I'd suggest you test with a known 404. If the page doesn't load the archive page, then it's because my service isn't seeing your referrer.
